### ISSUE TITLE
Thnks for sharing the repo. Does this repo works for WOZ 2.0 dataset as well? 

### ISSUE THREAD

**Issue by skmalviya** [renll/StateNet#6]

**Comment by renll** [comment]
Yes, it does.

**Comment by skmalviya** [comment]
Thanks for the quick response!
I find no script handling WOZ 2.0 dataset. **data.py** scripts seems to process only dstc2 corpus.
Then how can I reproduce the results on the WOZ?

**Comment by renll** [comment]
Oh, you may need to write a seperate data loading script for WOZ. It should be simple since WOZ2 has the same ontology as DSTC2 and the data json files for WOZ2 is well organized. The experiments on WOZ2 are done by the second author, thus you can contact him if you have any detailed problems for reproducing.

**Comment by skmalviya** [comment]
Ok sure... thanks for the kind help in understanding your work on DST.

**Comment by skmalviya** [comment]
Still not able to run it on WOZ2.0 dataset:
I have checked most part of the code is hard-wired to run on DSTC and without the proper readme instructions, it is difficult to make it run on WOZ2.0 corpus.
